<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\View' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/View.php';
include_once $this->targetDirs[3].'/src/Controller/Model.php';

return $this->services['App\Controller\View'] = new \App\Controller\View(${($_ = isset($this->services['App\Controller\Model']) ? $this->services['App\Controller\Model'] : $this->services['App\Controller\Model'] = new \App\Controller\Model()) && false ?: '_'});
