#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

hello_world:
  path: /
  controller: App\Controller\Controller::onLoad
  requirements:
    _method: GET
