<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWy9wmuc\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWy9wmuc/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWy9wmuc.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWy9wmuc\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerWy9wmuc\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Wy9wmuc',
    'container.build_id' => 'b70be4f3',
    'container.build_time' => 1517498398,
));
